all: help

.PHONY: help
help:
	@echo "make build - compiles everything"
	@echo "make package - build debian package"

configure: Makefile.am
	autoreconf -fvi

Makefile: configure
	( cd ${PWD} && ./$< --enable-debug=log )

.PHONY: build
build: Makefile
	( cd ${PWD} && ${MAKE} )

.PHONY: package
package:
	debuild -i -us -uc -b

# vim: set ts=8 sw=8 noet:
